
services:
  app:
    build: .
    container_name: langchain_app
    env_file:
      - ./.env
    volumes:
      - ./chatbot:/app/chatbot
      - ./chatbot.py:/app/chatbot.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
